name: python script
on: [push]
jobs:
  Run_Python_Scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        run: |
          import os
          print(os.environ['PATH'])
        shell: python
